Una prueba eliminando salida de variable answer

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -12,8 +12,8 @@ jobs:
           who-to-greet: '@zendejas'
       - name: Output the answer
         run: echo "The answer is ${{ steps.my-action.outputs.answer }}"
-      - name: Test the container
-        if: ${{ steps.my-action.outputs.answer != 42 }}
-        run: |
-          echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
-          exit 1
+#     - name: Test the container
+#       if: ${{ steps.my-action.outputs.answer != 42 }}
+#       run: |
+#         echo "::error file=entrypoint.sh,line=4,title=Error in container::The answer was not expected"
+#         exit 1
